### ISSUE TITLE
need custom injector

### ISSUE THREAD

**Issue by ghost** [techprimedev/Tech-CSGO-Injector#1]
I need to make a custom injector, which searches a file for valid email addresses. If the email address is in the database or file, you can continue, otherwise it displays an error message.
The DLL must be read from a folder on an internet site, in order to have the possibility of being updated without the user needing to be downloading updates all the time. can you budget for this?

**Comment by techzin** [comment]
If you need a custom LOADER for csgo, you can send message on my disc: TechZiN#7640
